# Generated by Django 3.2.9 on 2021-11-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_rollnumber_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollnumber',
            name='rollno',
            field=models.BigIntegerField(verbose_name='Roll Number'),
        ),
    ]
